<?php
require('functions/rss.php');
require('functions/javascript.php');
require('functions/profile.php');
require('functions/general.php');
require('functions/post-types.php');
require('functions/metaboxes.php');
require('functions/custom_taxonomies.php');
require('functions/event-posts.php');
require('functions/categories.php');
?>